# **Курс "Програмування на мові Python"**

## **Практичне зайняття №9**

### Тема: "Робота з функціями. Локальні та глобальні змінні"

### **Завдання 1 (3 бали)**

**Підрахувати визначник матриці, використовуючи правило перестановок.**

Функція random_matrix() призначена для створення квадратної матриці випадкових чисел. Її змінювати непотрібно.

Приклад використання методу permutations() для створення списку перестановок також подається у комірці з кодом.

1) Створити 3 функції: функцію створення списку перестановок, функцію підрахунку добутків та функцію підрахунку загальної суми.

2) Кожна функція має супроводжуватись рядком документації, що буде коротко описувати її призначення.

3) Розмірність квадратної матриці має вводитись користувачем з клавіатури. Підрахунки виконувати лише в тому разі, якщо користувач введе ціле додатне число.

4) Загальний результат повинен підраховуватись за допомогою композиції функцій.

За бажанням можна перевірити правильність роботи програми за допомогою функції np.linalg.det(a).

In [1]:
import numpy as np
import itertools
checker = True
while checker == True:
    dim = input('input dimensions: ')
    try:
        dim = int(dim)
        if dim < 2 or dim > 8:
            raise ValueError
        checker = False
    except:
        checker = True
def random_matrix(dim):
    """
    The function generates dim x dim array of integers
    between 0 and 10.
    """
    matrix = np.random.randint(10, size = (dim, dim))
    return matrix
def permutations(dim):
    '''
    This function permutates values by matrix dimensions set by the user
    '''
    txtdim = ''
    for i in range(1,dim+1):
        txtdim += str(i)
    t = list(itertools.permutations(txtdim, len(txtdim)))
    return t
matrix = random_matrix(dim)
def det(dim):
    '''
    This function finds a determinant for a matrix
    '''
    sum = 0
    for i0 in range(0,len(permutations(dim))):
        product = 1
        if ( int(permutations(dim)[i0][1]) == int(permutations(dim)[i0][0]) + 1 ) or ( int(permutations(dim)[i0][1]) == 1 and int(permutations(dim)[i0][0]) == int(dim)):
            for i in range(0,dim):
                mantissasign = 1
                product0 = matrix[i][int(permutations(dim)[i0][i])-1]
                product *= product0
    #            print(product0,end=" ")
        else:
            for i in range(0,dim):
                mantissasign = -1
                product0 = matrix[i][int(permutations(dim)[i0][i])-1]
                product *= product0
    #            print(product0,end=" ")
    #    print(mantissasign,end=" ")
        sum += product*mantissasign
    #    print(product*mantissasign)
    return sum
print(matrix)
print('det =',det(dim))
#print(permutations(dim))
#print(random_matrix.__doc__)

[[9 4 5]
 [5 6 7]
 [0 5 5]]
det = -20
